/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasClientes;

import Vistas.VentanaPrincipal;
import Clases.Contactos;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Naiara
 */
public class frm_AgregarClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_AgregarClientes
     */
    public JComboBox<String> getJcbCiudad() {
        return this.jcbCiudad;
    }

    public frm_AgregarClientes() {
        initComponents();
        jcbCiudad.setSelectedIndex(-1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlbDNI = new javax.swing.JLabel();
        jlbNombre = new javax.swing.JLabel();
        jlbApellido = new javax.swing.JLabel();
        jlbCiudad = new javax.swing.JLabel();
        jlbDomicilio = new javax.swing.JLabel();
        txtAgregarDNI = new javax.swing.JTextField();
        txtNombreAgregar = new javax.swing.JTextField();
        txtApellidoAgregar = new javax.swing.JTextField();
        txtDomicilioAgregar = new javax.swing.JTextField();
        jcbCiudad = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jlbTelefono = new javax.swing.JLabel();
        txtTeléfonoAgregar = new javax.swing.JTextField();
        btnGuardarAgregar = new javax.swing.JButton();
        btnSalirAgregar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");

        jlbDNI.setFont(new java.awt.Font("URW Gothic", 1, 11)); // NOI18N
        jlbDNI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbDNI.setText("DNI:");

        jlbNombre.setFont(new java.awt.Font("URW Gothic", 1, 11)); // NOI18N
        jlbNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbNombre.setText("Nombre:");

        jlbApellido.setFont(new java.awt.Font("URW Gothic", 1, 11)); // NOI18N
        jlbApellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbApellido.setText("Apellido:");

        jlbCiudad.setFont(new java.awt.Font("URW Gothic", 1, 11)); // NOI18N
        jlbCiudad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbCiudad.setText("Ciudad:");

        jlbDomicilio.setFont(new java.awt.Font("URW Gothic", 1, 11)); // NOI18N
        jlbDomicilio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbDomicilio.setText("Domicilio:");

        txtAgregarDNI.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        txtAgregarDNI.setToolTipText("txtDNI");

        txtNombreAgregar.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        txtNombreAgregar.setToolTipText("txtNombre");

        txtApellidoAgregar.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        txtDomicilioAgregar.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        txtDomicilioAgregar.setToolTipText("txtDomicilio");

        jcbCiudad.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jcbCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San Luis", "Villa Mercedes", "Juana Koslay", "Volcan" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbNombre)
                                            .addComponent(jlbDNI))
                                        .addGap(2, 2, 2))
                                    .addComponent(jlbApellido, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(16, 16, 16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbCiudad)
                                .addGap(21, 21, 21)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNombreAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAgregarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbDomicilio)
                        .addGap(10, 10, 10)
                        .addComponent(txtDomicilioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDNI)
                    .addComponent(txtAgregarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCiudad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDomicilio)
                    .addComponent(txtDomicilioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbTelefono.setFont(new java.awt.Font("URW Gothic", 1, 11)); // NOI18N
        jlbTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbTelefono.setText("Teléfono:");

        txtTeléfonoAgregar.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTelefono)
                .addGap(27, 27, 27)
                .addComponent(txtTeléfonoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTelefono)
                    .addComponent(txtTeléfonoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnGuardarAgregar.setText("Guardar");
        btnGuardarAgregar.setToolTipText("btnGuardar");
        btnGuardarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAgregarActionPerformed(evt);
            }
        });

        btnSalirAgregar.setText("Salir");
        btnSalirAgregar.setToolTipText("btnSalirClientes");
        btnSalirAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnGuardarAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalirAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarAgregar)
                    .addComponent(btnSalirAgregar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAgregarActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirAgregarActionPerformed

    private void btnGuardarAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAgregarActionPerformed
        Long telefono;
        String apellido = txtApellidoAgregar.getText();
        String domicilio = txtDomicilioAgregar.getText();
        String nombre = txtNombreAgregar.getText();
        int DNI;
        String ciudad = (String) jcbCiudad.getSelectedItem();

        try {

            if (apellido.isEmpty() || domicilio.isEmpty() || nombre.isEmpty() || ciudad.isEmpty()
                    || txtTeléfonoAgregar.getText().isEmpty() || txtAgregarDNI.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Faltan datos.");
            } else {
                telefono = Long.parseLong(txtTeléfonoAgregar.getText());
                DNI = Integer.parseInt(txtAgregarDNI.getText());
                if (VentanaPrincipal.directorio.claveExistente(telefono)) {
                    JOptionPane.showMessageDialog(this, "Telefono ya registrado.");
                } else {
                    Contactos contacto = new Contactos(DNI, nombre, apellido, ciudad, domicilio);
                    VentanaPrincipal.directorio.agregarContacto(telefono, contacto);
                    JOptionPane.showMessageDialog(this, "Se ha creado el cliente exitosamente.");
                    txtApellidoAgregar.setText("");
                    txtDomicilioAgregar.setText("");
                    txtNombreAgregar.setText("");
                    txtTeléfonoAgregar.setText("");
                    txtAgregarDNI.setText("");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Formato incorrecto de dato.");
        }
    }//GEN-LAST:event_btnGuardarAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarAgregar;
    private javax.swing.JButton btnSalirAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcbCiudad;
    private javax.swing.JLabel jlbApellido;
    private javax.swing.JLabel jlbCiudad;
    private javax.swing.JLabel jlbDNI;
    private javax.swing.JLabel jlbDomicilio;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JLabel jlbTelefono;
    private javax.swing.JTextField txtAgregarDNI;
    private javax.swing.JTextField txtApellidoAgregar;
    private javax.swing.JTextField txtDomicilioAgregar;
    private javax.swing.JTextField txtNombreAgregar;
    private javax.swing.JTextField txtTeléfonoAgregar;
    // End of variables declaration//GEN-END:variables
}
