/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VistasClientes;

import Clases.Contactos;
import Clases.Directorio_Telefónico;
import Vistas.VentanaPrincipal;
import java.util.ArrayList;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.DefaultListModel;

/**
 *
 * @author emadupre
 */
public class frmBuscar extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmBuscar
     */
    public void rellenarLista(Directorio_Telefónico directorio) {

        TreeMap<Long, Contactos> agendaTemporal = new TreeMap<>();
        agendaTemporal = directorio.getAgenda();
        DefaultListModel modelo = new DefaultListModel();
        for (Map.Entry<Long, Contactos> num : agendaTemporal.entrySet()) {
            modelo.addElement(num.getKey());
        }
        jListTelefonos.setModel(modelo);

    }

    public void filtrar() {
        String textoBusqueda = txtF_Telefono.getText();
        TreeMap<Long, Contactos> contactos = VentanaPrincipal.directorio.getAgenda();
        DefaultListModel modelo = (DefaultListModel) jListTelefonos.getModel();
        modelo.clear();
        for (Map.Entry<Long, Contactos> c : contactos.entrySet()) {
            String clave = String.valueOf(c.getKey());
            if (clave.startsWith(textoBusqueda)) {
                modelo.addElement(c.getKey());
            }
        }

    }

    public frmBuscar() {
        initComponents();
        rellenarLista(VentanaPrincipal.directorio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloBusqueda = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtF_Telefono = new javax.swing.JTextField();
        jScrollTelefono = new javax.swing.JScrollPane();
        jListTelefonos = new javax.swing.JList<>();
        separador = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        lblDNI = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        txtF_DNI = new javax.swing.JTextField();
        txtF_Apellido = new javax.swing.JTextField();
        txtF_Nombre = new javax.swing.JTextField();
        txtF_Ciudad = new javax.swing.JTextField();
        txtF_Domicilio = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        separador1 = new javax.swing.JSeparator();

        setTitle("Busqueda de Clientes");

        lblTituloBusqueda.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        lblTituloBusqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloBusqueda.setText("Busqueda de Clientes");
        lblTituloBusqueda.setToolTipText("");

        lblTelefono.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        lblTelefono.setText("Teléfono:");

        txtF_Telefono.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        txtF_Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtF_Telefono.setToolTipText("Ingrese numero de telefono");
        txtF_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF_TelefonoKeyReleased(evt);
            }
        });

        jScrollTelefono.setMinimumSize(new java.awt.Dimension(259, 131));

        jListTelefonos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListTelefonosValueChanged(evt);
            }
        });
        jScrollTelefono.setViewportView(jListTelefonos);

        separador2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblDNI.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        lblDNI.setText("DNI:");

        lblApellido.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        lblApellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellido.setText("Apellido:");

        lblNombre.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre:");

        lblCiudad.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        lblCiudad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCiudad.setText("Ciudad:");

        lblDomicilio.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        lblDomicilio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDomicilio.setText("Domicilio:");

        txtF_DNI.setEditable(false);
        txtF_DNI.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtF_Apellido.setEditable(false);
        txtF_Apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtF_Nombre.setEditable(false);
        txtF_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtF_Ciudad.setEditable(false);
        txtF_Ciudad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtF_Domicilio.setEditable(false);
        txtF_Domicilio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblTelefono)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(separador)
                            .addComponent(jScrollTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtF_Telefono, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDNI, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtF_Ciudad)
                            .addComponent(txtF_Apellido)
                            .addComponent(txtF_Nombre)
                            .addComponent(txtF_Domicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(txtF_DNI))))
                .addGap(34, 34, 34))
            .addComponent(separador1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtF_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefono))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(separador2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDNI)
                            .addComponent(txtF_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellido)
                            .addComponent(txtF_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCiudad)
                            .addComponent(txtF_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDomicilio)
                            .addComponent(txtF_Domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btnSalir)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jListTelefonosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTelefonosValueChanged
        if (!evt.getValueIsAdjusting() && jListTelefonos.getSelectedValue() != null) {
            Contactos contacto = VentanaPrincipal.directorio.buscarContacto(jListTelefonos.getSelectedValue());
            String dni = Integer.toString(contacto.getDni());
            txtF_Apellido.setText(contacto.getApellido());
            txtF_Ciudad.setText(contacto.getCiudad());
            txtF_DNI.setText(dni);
            txtF_Domicilio.setText(contacto.getDireccion());
            txtF_Nombre.setText(contacto.getNombre());
            txtF_Telefono.setText(Long.toString(jListTelefonos.getSelectedValue()));
        }
    }//GEN-LAST:event_jListTelefonosValueChanged

    private void txtF_TelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF_TelefonoKeyReleased
        filtrar();
    }//GEN-LAST:event_txtF_TelefonoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JList<Long> jListTelefonos;
    private javax.swing.JScrollPane jScrollTelefono;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloBusqueda;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JTextField txtF_Apellido;
    private javax.swing.JTextField txtF_Ciudad;
    private javax.swing.JTextField txtF_DNI;
    private javax.swing.JTextField txtF_Domicilio;
    private javax.swing.JTextField txtF_Nombre;
    private javax.swing.JTextField txtF_Telefono;
    // End of variables declaration//GEN-END:variables
}
