/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VistasCiudades;

import Vistas.VentanaPrincipal;
import VistasClientes.frm_AgregarClientes;
import javax.swing.JOptionPane;

/**
 *
 * @author emadupre
 */
public class frm_AgregarCiudad extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_AgregarCiudad
     */
    private frm_AgregarClientes ventanaTemporal;
    public frm_AgregarCiudad(frm_AgregarClientes ventana) {
        this.ventanaTemporal = ventana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAgregarCiudad = new javax.swing.JLabel();
        lblNombreAgregarCiudad = new javax.swing.JLabel();
        txtAgregarCiudad = new javax.swing.JTextField();
        btnGuardarAgregarCiudad = new javax.swing.JButton();
        btnSalirAgregarCiudad = new javax.swing.JButton();

        lblAgregarCiudad.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        lblAgregarCiudad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarCiudad.setText("Agregar Ciudad");

        lblNombreAgregarCiudad.setFont(new java.awt.Font("URW Gothic", 0, 14)); // NOI18N
        lblNombreAgregarCiudad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreAgregarCiudad.setText("Nombre Ciudad:");

        txtAgregarCiudad.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N

        btnGuardarAgregarCiudad.setFont(new java.awt.Font("URW Gothic", 0, 14)); // NOI18N
        btnGuardarAgregarCiudad.setText("Guardar");
        btnGuardarAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAgregarCiudadActionPerformed(evt);
            }
        });

        btnSalirAgregarCiudad.setFont(new java.awt.Font("URW Gothic", 0, 14)); // NOI18N
        btnSalirAgregarCiudad.setText("Salir");
        btnSalirAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAgregarCiudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAgregarCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblNombreAgregarCiudad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardarAgregarCiudad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalirAgregarCiudad))
                    .addComponent(txtAgregarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblAgregarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAgregarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreAgregarCiudad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirAgregarCiudad)
                    .addComponent(btnGuardarAgregarCiudad))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAgregarCiudadActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirAgregarCiudadActionPerformed

    /*
    Compruebo si el campo no está vacio y lo añado a jComboBox de agregarClientes y 
    posteriormente lo reordeno, en caso de estar vacio el textField largo un mensaje
    que no escribio la ciudad.
    */
    private void btnGuardarAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAgregarCiudadActionPerformed
        if(!txtAgregarCiudad.getText().isEmpty()){
            String ciudad = txtAgregarCiudad.getText();
            ventanaTemporal.getJcbCiudad().addItem(ciudad);
            VentanaPrincipal.rellenoOrdenAlfabeticoComboBox(ventanaTemporal.getJcbCiudad());
            JOptionPane.showMessageDialog(this, "Ciudad agregada exitosamente.");
            txtAgregarCiudad.setText("");
        } else{
         JOptionPane.showMessageDialog(this, "No ha ingresado la ciudad a agregar.");
        }
        
    }//GEN-LAST:event_btnGuardarAgregarCiudadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarAgregarCiudad;
    private javax.swing.JButton btnSalirAgregarCiudad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgregarCiudad;
    private javax.swing.JLabel lblNombreAgregarCiudad;
    private javax.swing.JTextField txtAgregarCiudad;
    // End of variables declaration//GEN-END:variables
}
