/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VistasDirectorio;

/**
 *
 * @author emadupre
 */
public class frm_BuscarTelefonoPorApellido extends javax.swing.JInternalFrame {

    /**
     * Creates new form buscarTelefonoPorApellido
     */
    public frm_BuscarTelefonoPorApellido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloBusquedaTelefono = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        txtF_Apellido = new javax.swing.JTextField();
        separador2 = new javax.swing.JSeparator();
        jScrollApellidos = new javax.swing.JScrollPane();
        jListApellidos = new javax.swing.JList<>();
        jScrollTabla = new javax.swing.JScrollPane();
        jTableContactos = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();

        lblTituloBusquedaTelefono.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        lblTituloBusquedaTelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloBusquedaTelefono.setText("Buscar Teléfono Por Apellido");
        lblTituloBusquedaTelefono.setToolTipText("");

        lblApellido.setFont(new java.awt.Font("URW Gothic", 1, 13)); // NOI18N
        lblApellido.setText("Apellido:");

        txtF_Apellido.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        txtF_Apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtF_Apellido.setToolTipText("Ingrese numero de telefono");

        separador2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jScrollApellidos.setViewportView(jListApellidos);

        jTableContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Apellido", "Nombre", "Direccion", "Ciudad", "Telefono"
            }
        ));
        jTableContactos.setName(""); // NOI18N
        jScrollTabla.setViewportView(jTableContactos);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloBusquedaTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblApellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtF_Apellido)
                                    .addComponent(jScrollApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTituloBusquedaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtF_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollApellidos))
                    .addComponent(separador2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jScrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JList<String> jListApellidos;
    private javax.swing.JScrollPane jScrollApellidos;
    private javax.swing.JScrollPane jScrollTabla;
    private javax.swing.JTable jTableContactos;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblTituloBusquedaTelefono;
    private javax.swing.JSeparator separador2;
    private javax.swing.JTextField txtF_Apellido;
    // End of variables declaration//GEN-END:variables
}
