/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasDirectorio;

import Clases.Contactos;
import Clases.Directorio_Telefónico;
import Vistas.VentanaPrincipal;
import VistasClientes.frm_AgregarClientes;
import java.util.ArrayList;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Naiara
 */
public class frm_BuscarClienteCiudad extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_BuscarClienteCiudad
     */
    private frm_AgregarClientes temporal;
    DefaultTableModel modeloTable = new DefaultTableModel();
    public void rellenarCiudades(JComboBox caja) {
        DefaultComboBoxModel cajaCiudades = (DefaultComboBoxModel) caja.getModel();
        jcbCiudad.setModel(cajaCiudades);

    }

    public void rellenarTabla(Directorio_Telefónico directorio, ArrayList<Contactos> contac) {
        TreeMap<Long, Contactos> direc = new TreeMap<>();
        modeloTable = (DefaultTableModel) jTable1.getModel();
        modeloTable.setRowCount(0);
        direc = directorio.getAgenda();
        for (Contactos cont : contac) {
            for (Map.Entry<Long, Contactos> c : direc.entrySet()) {
                Contactos usuario = c.getValue();
                if (usuario.getCiudad().equals(cont.getCiudad())) {
                    Long telefono = c.getKey();
                    modeloTable.addRow(new Object[]{cont.getDni(), cont.getNombre(),
                        cont.getApellido(), cont.getCiudad(), cont.getDireccion(), telefono});
                }
            }
        }
    }

    public frm_BuscarClienteCiudad(frm_AgregarClientes ventana) {
        initComponents();
        this.temporal = ventana;
        VentanaPrincipal.armarCabeceraDeContactosTablas(jTable1);
        rellenarCiudades(temporal.getJcbCiudad());
        jcbCiudad.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBuscarPorCiudad = new javax.swing.JPanel();
        jblBuscarporCiudad = new javax.swing.JLabel();
        jblCiudades = new javax.swing.JLabel();
        jcbCiudad = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSalirDirectorioCiudad = new javax.swing.JButton();

        jPanelBuscarPorCiudad.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jblBuscarporCiudad.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        jblBuscarporCiudad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblBuscarporCiudad.setText("Buscar Clientes de Directorio por Ciudad");

        jblCiudades.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        jblCiudades.setText("Ciudades:");

        jcbCiudad.setBackground(new java.awt.Color(51, 153, 255));
        jcbCiudad.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        jcbCiudad.setForeground(new java.awt.Color(51, 51, 51));
        jcbCiudad.setToolTipText("jcbCiudad2");
        jcbCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCiudadActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTable1);

        btnSalirDirectorioCiudad.setFont(new java.awt.Font("URW Gothic", 0, 13)); // NOI18N
        btnSalirDirectorioCiudad.setText("Salir");
        btnSalirDirectorioCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirDirectorioCiudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarPorCiudadLayout = new javax.swing.GroupLayout(jPanelBuscarPorCiudad);
        jPanelBuscarPorCiudad.setLayout(jPanelBuscarPorCiudadLayout);
        jPanelBuscarPorCiudadLayout.setHorizontalGroup(
            jPanelBuscarPorCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblBuscarporCiudad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelBuscarPorCiudadLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelBuscarPorCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalirDirectorioCiudad)
                    .addGroup(jPanelBuscarPorCiudadLayout.createSequentialGroup()
                        .addGroup(jPanelBuscarPorCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblCiudades)
                            .addComponent(jcbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBuscarPorCiudadLayout.setVerticalGroup(
            jPanelBuscarPorCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarPorCiudadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblBuscarporCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarPorCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarPorCiudadLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jblCiudades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnSalirDirectorioCiudad)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBuscarPorCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBuscarPorCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirDirectorioCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirDirectorioCiudadActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirDirectorioCiudadActionPerformed

    private void jcbCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCiudadActionPerformed
        String ciudad = (String) jcbCiudad.getSelectedItem();
        ArrayList<Contactos> contactos = new ArrayList<>();
        contactos.clear();
        for (Map.Entry<Long, Contactos> cont : VentanaPrincipal.directorio.getAgenda().entrySet()) {
            Contactos cliente = cont.getValue();
            if (cliente.getCiudad().equals(ciudad)) {
                contactos.add(cliente);
            }
        }
        
        rellenarTabla(VentanaPrincipal.directorio, contactos);
    }//GEN-LAST:event_jcbCiudadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirDirectorioCiudad;
    private javax.swing.JPanel jPanelBuscarPorCiudad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jblBuscarporCiudad;
    private javax.swing.JLabel jblCiudades;
    private javax.swing.JComboBox<String> jcbCiudad;
    // End of variables declaration//GEN-END:variables
}
