/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Directorio_Telefónico;
import VistasClientes.AgregarClientes;

/**
 *
 * @author Enzo_2
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public static final Directorio_Telefónico directorio = new Directorio_Telefónico();
    public VentanaPrincipal() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        clientesMenu = new javax.swing.JMenu();
        agregarCliente = new javax.swing.JMenuItem();
        buscarCliente = new javax.swing.JMenuItem();
        borrarCliente = new javax.swing.JMenuItem();
        directorioMenu = new javax.swing.JMenu();
        buscarClientePorCiudad = new javax.swing.JMenuItem();
        buscarTelPorApellido = new javax.swing.JMenuItem();
        ciudadesMenu = new javax.swing.JMenu();
        agregarCiudad = new javax.swing.JMenuItem();
        salirMenu = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        clientesMenu.setText("Clientes");

        agregarCliente.setText("Agregar Cliente");
        agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClienteActionPerformed(evt);
            }
        });
        clientesMenu.add(agregarCliente);

        buscarCliente.setText("Buscar Cliente");
        clientesMenu.add(buscarCliente);

        borrarCliente.setText("Borrar Cliente");
        clientesMenu.add(borrarCliente);

        jMenuBar1.add(clientesMenu);

        directorioMenu.setText("Directorio");

        buscarClientePorCiudad.setText("Buscar Clientes por Ciudad");
        directorioMenu.add(buscarClientePorCiudad);

        buscarTelPorApellido.setText("Buscar Teléfono por Apellido");
        directorioMenu.add(buscarTelPorApellido);

        jMenuBar1.add(directorioMenu);

        ciudadesMenu.setText("Ciudades");

        agregarCiudad.setText("Agregar Ciudad");
        agregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCiudadActionPerformed(evt);
            }
        });
        ciudadesMenu.add(agregarCiudad);

        jMenuBar1.add(ciudadesMenu);

        salirMenu.setText("Salir");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        salirMenu.add(btnSalir);

        jMenuBar1.add(salirMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void agregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCiudadActionPerformed
        
    }//GEN-LAST:event_agregarCiudadActionPerformed

    private void agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClienteActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
         AgregarClientes vistaClienteAgregar = new AgregarClientes();
         vistaClienteAgregar.setVisible(true);
         escritorio.add(vistaClienteAgregar);
         escritorio.moveToFront(vistaClienteAgregar);
    }//GEN-LAST:event_agregarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregarCiudad;
    private javax.swing.JMenuItem agregarCliente;
    private javax.swing.JMenuItem borrarCliente;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem buscarCliente;
    private javax.swing.JMenuItem buscarClientePorCiudad;
    private javax.swing.JMenuItem buscarTelPorApellido;
    private javax.swing.JMenu ciudadesMenu;
    private javax.swing.JMenu clientesMenu;
    private javax.swing.JMenu directorioMenu;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu salirMenu;
    // End of variables declaration//GEN-END:variables
}
